spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:~/data/demo
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: "12345678901234567890123456789010"

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

---
spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop
