spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: "12345678901234567890123456789010"

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

