spring:
  datasource:
#    url: jdbc:h2:~/data/demo
    url: jdbc:mariadb://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true
#    ?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: "12345678901234567890123456789010"

server:
  servlet:
     encoding:
       charset: UTF-8
       force: true
