spring:
  datasource:
    url: jdbc:h2:~/data/demo
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: "12345678901234567890123456789010"

---

spring:
  datasource:
    profiles: mariadb
    url: jdbc:mariadb://mariadb:3306/test
    username: root
    password: root1234