spring:
  datasource:
    url: jdbc:h2:~/data/demo
#    url: jdbc:mariadb://localhost:3306/test
#    username: root
#    password: root1234
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: "12345678901234567890123456789010"


# mariadb profile을 쓸 때 위 내용을 덮어서 쓰고 싶을 때
---
spring:
  profiles: mariadb
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: root1234
