spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: "sample"
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
---
spring:
  profiles: mariadb
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: sample-name
    password: sample-password
  jpa:
    hibernate:
      ddl-auto: create-drop
