spring:
  datasource:
    url: jdbc:h2:~/data/test
#    url: jdbc:mariadb://localhost:3306/test
  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: "12345678901234567890123456789010"

#---
#
#spring:
#  profiles: mariadb
#  datasource:
#    url: jdbc:mariadb://mariadb:3306:test
#    username: root
#    password: apsssword
